# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   labels:
#     app: gitops-webapp
#   name: gitops-webapp
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: gitops-webapp
#   template:
#     metadata:
#       labels:
#         app: gitops-webapp
#     spec:
#       containers:
#       - image: registry.gitlab.com/andrew.kaczynski/gitops-webapp:1.0
#         name: gitops-webapp
#         imagePullPolicy: Always
#         ports:
#         - containerPort: 8080
#           name: http
#         env:
#         - name: APP_PORT
#           value: "8080"

apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: guestbook-ui
        ports:
        - containerPort: 80