# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     app: gitops-webapp
#   name: gitops-webapp-svc
# spec:
#   type: NodePort
#   ports:
#   - port: 80
#     name: http
#     protocol: TCP
#     targetPort: 8080
#   selector:
#     app: gitops-webapp

apiVersion: v1
kind: Service
metadata:
  name: gitops-webapp-svc
spec:
  selector:
    app: gitops-webapp
    tier: back
  ports:
    - port: 8080