variables:
  APP_NAME: gitops-argocd-demo
  CI_REGISTRY: https://index.docker.io/v1/
  CI_REGISTRY_IMAGE: mistersoh/$APP_NAME
#   CD_CHART_REPO: cicd-test
#   CD_GIT_REPOSITORY: http://192.168.108.46:8081/root/$CD_CHART_REPO.git
#   CD_MANIFEST_FILE: Chart.yaml
#   DOCKER_DRIVER: overlay2
#   DOCKER_TLS_CERTDIR: ""
#   TAG: $CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA

# stages:
#   - build
#   - publish
#   - deploy-dev
#   - deploy-prod

# build:
#   stage: build
#   image:
#     name: golang:1.13.1
#   script:
#     - go build -o main main.go
#   artifacts:
#     paths:
#       - main
#   variables:
#     CGO_ENABLED: 0

# publish:
#   stage: publish
#   image:
#     name: gcr.io/kaniko-project/executor:debug
#     entrypoint: [""]
#   script:
#     - mkdir -p /kaniko/.docker
#     - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
#     - cat /kaniko/.docker/config.json
#     - >-
#       /kaniko/executor
#       --context "${CI_PROJECT_DIR}"
#       --dockerfile "./Dockerfile"
#       --destination "${CI_REGISTRY_IMAGE}:$TAG"


# deploy-dev:
#   stage: deploy-dev
#   image: alpine:3.8
#   before_script:
#     - apk add --no-cache git curl bash
#     - curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
#     - mv kustomize /usr/local/bin/
#     - git remote set-url origin https://${CI_USERNAME}:${CI_PUSH_TOKEN}@192.168.108.46:8081/root/cicd-test.git
#     - git config --global user.email "gitlab@gitlab.com"
#     - git config --global user.name "GitLab CI/CD"
#   script:
#     - git checkout -B master
#     - cd deployment/dev
#     - kustomize edit set image $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
#     - cat kustomization.yaml
#     - git commit -am 'DEV image update'
#     - git push origin master


# deploy-prod:
#   stage: deploy-prod
#   image: alpine:3.8
#   before_script:
#     - apk add --no-cache git curl bash
#     - curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
#     - mv kustomize /usr/local/bin/
#     - git remote set-url origin https://${CI_USERNAME}:${CI_PUSH_TOKEN}@192.168.108.46:8081/root/cicd-test.git
#     - git config --global user.email "gitlab@gitlab.com"
#     - git config --global user.name "GitLab CI/CD"
#   script:
#     - git checkout -B master
#     - git pull origin master
#     - cd deployment/prod
#     - kustomize edit set image $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
#     - cat kustomization.yaml
#     - git commit -am 'PROD image update'
#     - git push origin master


stages:
  - build
  - publish
  - deploy-dev
  - deploy-prod

build:
  stage: build
  image:
    name: golang:1.13.1
  script:
    - go build -o main main.go
  artifacts:
    paths:
      - main
  variables:
    CGO_ENABLED: 0

# publish:
#   stage: publish
#   image:
#     name: gcr.io/kaniko-project/executor:debug
#     entrypoint: [""]
#   script:
#     - mkdir -p /kaniko/.docker
#     - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
#     - cat /kaniko/.docker/config.json
#     - >-
#       /kaniko/executor
#       --context "${CI_PROJECT_DIR}"
#       --dockerfile "./Dockerfile"
#       --destination "${CI_REGISTRY_IMAGE}:$TAG"


publish:
  stage: publish
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile ./Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  dependencies:
    - build  
  only:
    - main

deploy-dev:
  stage: deploy-dev
  image: maven:latest
  before_script:
    - yum install -y git
    - mv kustomize /usr/local/bin/
    - git remote set-url origin https://${CI_USERNAME}:${CI_PUSH_TOKEN}@192.168.108.46:8081/root/cicd-test.git
    - git config --global user.email "mistersoh@naver.com"
    - git config --global user.name "WWSOH"
  script:
    - git checkout -B master
    - cd deployment/dev
    - kustomize edit set image $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - cat kustomization.yaml
    - git commit -am '[skip ci] DEV image update'
    - git push origin master
  only:
    - main

deploy-prod:
  stage: deploy-prod
  image: maven:latest
  before_script:
    - yum install -y git
    - mv kustomize /usr/local/bin/
    - git remote set-url origin https://${CI_USERNAME}:${CI_PUSH_TOKEN}@192.168.108.46:8081/root/cicd-test.git
    - git config --global user.email "mistersoh@naver.com"
    - git config --global user.name "WWSOH"
  script:
    - git checkout -B master
    - git pull origin master
    - cd deployment/prod
    - kustomize edit set image $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - cat kustomization.yaml
    - git commit -am '[skip ci] PROD image update'
    - git push origin master
  only:
    - main
  when: manual
