stages:
  - build
  - test
  - publish
  - deploy

build:
  stage: build
  image:
    name: golang:1.13.1
  script:
    - go build -o main main.go
  artifacts:
    paths:
      - main
  variables:
    CGO_ENABLED: 0

test:
  stage: test
  script:
    - echo "Coverage checking"
    - sleep 10
    - echo "coverage is 90%"

publish:
  stage: publish
  # image:
  #   name: gcr.io/kaniko-project/executor:debug
  #   entrypoint: [""]
  script:
    - echo "publishing"
    - sleep 10
    - echo "publishing done"
  #   - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
  #   - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile ./Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  # dependencies:
  #   - build  
  # only:
  #   - master

deploy-dev:
  stage: deploy
  # image: alpine:3.8
  # before_script:
  #   - apk add --no-cache git curl bash
  #   - curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
  #   - mv kustomize /usr/local/bin/
  #   - git remote set-url origin https://${CI_USERNAME}:${CI_PUSH_TOKEN}@gitlab.com/root/cicd-test.git
  #   - git config --global user.email "gitlab@gitlab.com"
  #   - git config --global user.name "GitLab CI/CD"
  script:
    - echo "deploying dev"
    - sleep 10
    - echo "deploy done"
  #   - git checkout -B master
  #   - cd deployment/dev
  #   - kustomize edit set image $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  #   - cat kustomization.yaml
  #   - git commit -am 'DEV image update'
  #   - git push origin master
  # only:
  #   - master

deploy-prod:
  stage: deploy
#   image: alpine:3.8
#   before_script:
#     - apk add --no-cache git curl bash
#     - curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
#     - mv kustomize /usr/local/bin/
#     - git remote set-url origin https://${CI_USERNAME}:${CI_PUSH_TOKEN}@gitlab.com/andrew.kaczynski/gitops-webapp.git
#     - git config --global user.email "gitlab@gitlab.com"
#     - git config --global user.name "GitLab CI/CD"
  script:
    - echo "deploying prod"
    - sleep 10
    - echo "deploy done"
#     - git checkout -B master
#     - git pull origin master
#     - cd deployment/prod
#     - kustomize edit set image $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
#     - cat kustomization.yaml
#     - git commit -am '[skip ci] PROD image update'
#     - git push origin master
#   only:
#     - master
  # when: manual
